// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package biz is a generated GoMock package.
package biz

import (
	reflect "reflect"

	model "github.com/blackhorseya/project-goapi/entity/domain/user/model"
	contextx "github.com/blackhorseya/project-goapi/pkg/contextx"
	gomock "github.com/golang/mock/gomock"
)

// MockBizer is a mock of Bizer interface.
type MockBizer struct {
	ctrl     *gomock.Controller
	recorder *MockBizerMockRecorder
}

// MockBizerMockRecorder is the mock recorder for MockBizer.
type MockBizerMockRecorder struct {
	mock *MockBizer
}

// NewMockBizer creates a new mock instance.
func NewMockBizer(ctrl *gomock.Controller) *MockBizer {
	mock := &MockBizer{ctrl: ctrl}
	mock.recorder = &MockBizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBizer) EXPECT() *MockBizerMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockBizer) Login(ctx contextx.Contextx, username, password string) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, username, password)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockBizerMockRecorder) Login(ctx, username, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockBizer)(nil).Login), ctx, username, password)
}

// Register mocks base method.
func (m *MockBizer) Register(ctx contextx.Contextx, username, password string) (*model.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, username, password)
	ret0, _ := ret[0].(*model.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockBizerMockRecorder) Register(ctx, username, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockBizer)(nil).Register), ctx, username, password)
}
