// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package biz

import (
	"github.com/blackhorseya/project-goapi/entity/domain/user/biz"
	"github.com/blackhorseya/project-goapi/internal/app/domain/user/biz/db"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateBizer(db2 db.ReaderWriter) biz.Bizer {
	bizer := NewImpl(db2)
	return bizer
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
